/*
 * The MIT License
 *
 * Copyright 2024 Laboratorio de Bioquímica e Química de Proteínas / 
 * Instituto de Ciências Biológicas / Universidade de Brasília
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package actr;

import static actr.CalibradorACTR3.SECONDS_PER_WELL;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JLabel;


public class FrmImpedancias extends javax.swing.JFrame {

    
    private boolean close = false;
    private final Well[] wellList = {Well.WELL_A1,Well.WELL_B1,Well.WELL_C1,Well.WELL_D1,
                                Well.WELL_E1, Well.WELL_F1, Well.WELL_G1, Well.WELL_H1,
                                Well.WELL_A2, Well.WELL_B2, Well.WELL_C2, Well.WELL_D2,
                                Well.WELL_E2, Well.WELL_F2, Well.WELL_G2, Well.WELL_H2};
    
    
    /**
     * Creates new form FrmCal
     */
    public FrmImpedancias() {
        initComponents();
        this.pack();
        
        
        
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                loop();
            }
        });
        t.start();
    }
    
    private void loop()
    {
        DecimalFormat df = new DecimalFormat("#,###.000");
        
        JLabel[] lblWell_List = {lblPocoA1, lblPocoB1, lblPocoC1, lblPocoD1,
                                        lblPocoE1, lblPocoF1, lblPocoG1, lblPocoH1,
                                        lblPocoA2, lblPocoB2, lblPocoC2, lblPocoD2,
                                        lblPocoE2, lblPocoF2, lblPocoG2, lblPocoH2};

        
        ImpedanceReader reader = ImpedanceReaderFactory.getImpedanceReader();
        Calibrador calibrador = new CalibradorACTR3();
        reader.start();
        while(!close)
        {
            Date start = new Date();
            calibrador.calibrar();
            for(int i=0; i<wellList.length; i++)
            {
                Leitura l = reader.read(wellList[i], SECONDS_PER_WELL, calibrador);
                JLabel lblWell = lblWell_List[i];
                String texto = lblWell.getText().substring(0, 9);
                if(l.statusLeitura==StatusLeitura.Normal)
                {
                    texto += df.format(l.impedancia) + " ohms (" + l.numSamples + " leituras)";
                }
                else
                {
                    texto += l.statusLeitura.toString() + " / " + df.format(l.impedancia) + " ohms (" + l.numSamples + " leituras)";
                }
                lblWell.setText(texto);
                
                
                if(close) break;
                this.pack();
            }
            
            double t = ((new Date()).getTime() - start.getTime() )/1000.0;
            lblTempoTotal.setText("Tempo total: " + df.format(t) + " segundos");
        }
        
        reader.end();
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        lblPocoA1 = new javax.swing.JLabel();
        lblPocoB1 = new javax.swing.JLabel();
        lblPocoC1 = new javax.swing.JLabel();
        lblPocoD1 = new javax.swing.JLabel();
        lblPocoE1 = new javax.swing.JLabel();
        lblPocoF1 = new javax.swing.JLabel();
        lblPocoG1 = new javax.swing.JLabel();
        lblPocoH1 = new javax.swing.JLabel();
        lblPocoA2 = new javax.swing.JLabel();
        lblPocoB2 = new javax.swing.JLabel();
        lblPocoC2 = new javax.swing.JLabel();
        lblPocoD2 = new javax.swing.JLabel();
        lblPocoE2 = new javax.swing.JLabel();
        lblPocoF2 = new javax.swing.JLabel();
        lblPocoG2 = new javax.swing.JLabel();
        lblPocoH2 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lblTempoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impedâncias");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPocoA1.setText("Poço A1: 0 ohms");

        lblPocoB1.setText("Poço B1: 0 ohms");

        lblPocoC1.setText("Poço C1: 0 ohms");

        lblPocoD1.setText("Poço D1: 0 ohms");

        lblPocoE1.setText("Poço E1: 0 ohms");

        lblPocoF1.setText("Poço F1: 0 ohms");

        lblPocoG1.setText("Poço G1: 0 ohms");

        lblPocoH1.setText("Poço H1: 0 ohms");

        lblPocoA2.setText("Poço A2: 0 ohms");

        lblPocoB2.setText("Poço B2: 0 ohms");

        lblPocoC2.setText("Poço C2: 0 ohms");

        lblPocoD2.setText("Poço D2: 0 ohms");

        lblPocoE2.setText("Poço E2: 0 ohms");

        lblPocoF2.setText("Poço F2: 0 ohms");

        lblPocoG2.setText("Poço G2: 0 ohms");

        lblPocoH2.setText("Poço H2: 0 ohms");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPocoA1)
                    .addComponent(lblPocoB1)
                    .addComponent(lblPocoC1)
                    .addComponent(lblPocoD1)
                    .addComponent(lblPocoE1)
                    .addComponent(lblPocoF1)
                    .addComponent(lblPocoG1)
                    .addComponent(lblPocoH1)
                    .addComponent(lblPocoA2)
                    .addComponent(lblPocoB2)
                    .addComponent(lblPocoC2)
                    .addComponent(lblPocoD2)
                    .addComponent(lblPocoE2)
                    .addComponent(lblPocoF2)
                    .addComponent(lblPocoG2)
                    .addComponent(lblPocoH2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPocoA1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoE1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoF1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoA2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoC2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoD2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoE2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoF2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoG2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPocoH2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblTempoTotal.setText("Tempo total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTempoTotal)
                            .addComponent(btnFechar))
                        .addGap(0, 348, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTempoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        close = true;
    }//GEN-LAST:event_btnFecharActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close=true;
    }//GEN-LAST:event_formWindowClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblPocoA1;
    private javax.swing.JLabel lblPocoA2;
    private javax.swing.JLabel lblPocoB1;
    private javax.swing.JLabel lblPocoB2;
    private javax.swing.JLabel lblPocoC1;
    private javax.swing.JLabel lblPocoC2;
    private javax.swing.JLabel lblPocoD1;
    private javax.swing.JLabel lblPocoD2;
    private javax.swing.JLabel lblPocoE1;
    private javax.swing.JLabel lblPocoE2;
    private javax.swing.JLabel lblPocoF1;
    private javax.swing.JLabel lblPocoF2;
    private javax.swing.JLabel lblPocoG1;
    private javax.swing.JLabel lblPocoG2;
    private javax.swing.JLabel lblPocoH1;
    private javax.swing.JLabel lblPocoH2;
    private javax.swing.JLabel lblTempoTotal;
    // End of variables declaration//GEN-END:variables




}

